apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata: 
  labels: 
    name: pipeline-aceimage-buildconfig
  name: pipeline-aceimage-buildconfig
  namespace: ace
spec: 
  output: 
    to: 
      kind: ImageStreamTag
      name: "pipeline-aceimage:latest"
      namespace: ace
  source: 
    dockerfile: |
        FROM ace-prod-10-r1:latest-amd64
        COPY SimpleHTTPAppTest.bar /home/aceuser/initial-config/bars/SimpleHTTPAppTest.bar
    type: dockerfile
  strategy: 
    dockerStrategy: 
      from: 
        kind: ImageStreamTag
        name: "ace-prod-10-r1:latest-amd64"
        namespace: ace
    type: Docker
  triggers: []